# Generated by Django 5.2.6 on 2025-10-05 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
        ('sources', '0006_remove_rawopportunity_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('cleaned_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending LLM Processing'), ('processed', 'Processed Successfully'), ('garbage', 'Garbage / Irrelevant')], default='pending', max_length=20)),
                ('raw_opportunity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaned', to='sources.rawopportunity')),
            ],
        ),
    ]
