# Generated by Django 5.2.6 on 2025-11-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_cleanedopportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedopportunity',
            name='matching_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched')], default='pending', max_length=20),
        ),
    ]
