# Generated by Django 5.2.6 on 2025-10-01 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitymatch',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='processing.processedopportunity'),
        ),
        migrations.AddField(
            model_name='opportunitymatch',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matching.startup'),
        ),
    ]
