# Generated by Django 5.2.6 on 2025-10-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitymatch',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
