# Generated by Django 5.2.6 on 2025-10-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_opportunitymatch_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitymatch',
            name='mailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
