# Generated by Django 5.2.6 on 2025-10-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('static', 'Static HTML Page'), ('dynamic', 'Dynamic JS Page'), ('api', 'API'), ('rss', 'RSS Feed'), ('file', 'PDF/Image')], max_length=20)),
                ('source_name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('raw_content', models.TextField()),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('valid', 'Valid Opportunity'), ('garbage', 'Garbage / Irrelevant')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SourceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('static', 'Static HTML Page'), ('dynamic', 'Dynamic JS Page'), ('api', 'API'), ('rss', 'RSS Feed'), ('file', 'PDF/Image')], max_length=20)),
                ('base_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
