# Generated by Django 5.2.6 on 2025-10-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceregistry',
            name='source_type',
            field=models.CharField(choices=[('static', 'Static HTML Page'), ('dynamic', 'Dynamic JS Page'), ('rss', 'RSS Feed'), ('file', 'PDF/Image')], max_length=20),
        ),
    ]
