# Generated by Django 5.2.6 on 2025-10-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_alter_sourceregistry_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawopportunity',
            name='file_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawopportunity',
            name='source_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rawopportunity',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
