# Generated by Django 5.2.6 on 2025-10-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_alter_rawopportunity_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceregistry',
            name='source_type',
            field=models.CharField(choices=[('google', 'Google Search Result'), ('custom', 'Manually Added Source')], max_length=20),
        ),
    ]
