# Generated by Django 5.2.6 on 2025-10-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_alter_sourceregistry_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceregistry',
            name='web_type',
            field=models.CharField(choices=[('static', 'Static HTML Page'), ('dynamic', 'Dynamic JS Page')], default='static', max_length=20),
        ),
    ]
