# Generated by Django 5.2.6 on 2025-10-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_sourceregistry_web_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawopportunity',
            name='processed',
        ),
        migrations.AlterField(
            model_name='rawopportunity',
            name='status',
            field=models.CharField(choices=[('pending', ' Pending Processing '), ('cleaned', ' Cleaned Successfully ')], default='pending', max_length=20),
        ),
    ]
