# Generated by Django 5.2.6 on 2025-11-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_remove_rawopportunity_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceregistry',
            name='search_term',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
